### ISSUE TITLE
[bug] SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [accuknox/discovery-engine#711]
This issue is happening when we run discovery-engine locally.

Error:
```sh
➜  src git:(dev) CONF_FILE_NAME=local-file ./knoxAutoPolicy
11:25AM INF libs/common.go:76 > BUILD-INFO: commit:9aaee57, branch: dev, date: 2023-04-17T05:53:08Z, version: 0.1
11:25AM INF main.go:33 > NETWORK-POLICY: {OperationMode:1 OperationTrigger:5 CronJobTimeInterval:@every 0h0m10s OneTimeJobTimeSelection: NetworkLogLimit:10000 NetworkLogFrom:kubearmor NetworkLogFile: NetworkPolicyTo:db NetworkPolicyDir:./ NsFilter:[] NsNotFilter:[kube-system] NetPolicyTypes:3 NetPolicyRuleTypes:1023 NetPolicyCIDRBits:32 NetLogFilters:[] NetPolicyL3Level:1 NetPolicyL4Level:1 NetPolicyL7Level:1 NetSkipCertVerification:true}
11:25AM INF main.go:34 > CILIUM: {HubbleURL:localhost HubblePort:4245}
11:25AM INF main.go:35 > SYSTEM-POLICY: {OperationMode:1 OperationTrigger:5 CronJobTimeInterval:@every 0h0m10s OneTimeJobTimeSelection: SystemLogLimit:10000 SystemLogFrom:kubearmor SystemLogFile: SystemPolicyTo:db SystemPolicyDir:./ SysPolicyTypes:7 DeprecateOldMode:true SystemLogFilters:[] NsFilter:[] NsNotFilter:[kube-system] FromSourceFilter:[knoxAutoPolicy] ProcessFromSource:true FileFromSource:true}
11:25AM INF main.go:36 > KUBEARMOR: {KubeArmorRelayURL:localhost KubeArmorRelayPort:32767}
11:25AM INF networkpolicy/networkPolicy.go:2362 > Auto network policy discovery cron job started
11:25AM INF systempolicy/systemPolicy.go:1503 > Auto system policy discovery cron job started
11:25AM INF observability/observability.go:79 > Observability cron job started
11:25AM INF observability/observability.go:97 > Publisher cron job started
11:25AM INF recommendpolicy/recommendPolicy.go:73 > Recommended policy cron job started
11:25AM INF recommendpolicy/downloadTemplates.go:117 > Latest recommendation downloaded and updated
11:25AM INF recommendpolicy/recommendPolicy.go:165 > Generating hardening policy for deployment: vault-agent-injector in namespace: default
11:25AM INF recommendpolicy/recommendPolicy.go:165 > Generating hardening policy for deployment: mysql in namespace: wordpress-mysql
11:25AM INF recommendpolicy/recommendPolicy.go:165 > Generating hardening policy for deployment: wordpress in namespace: wordpress-mysql
11:25AM INF main.go:59 > gRPC server on 9089 port started
11:25AM INF networkpolicy/helperFunctions.go:297 > Get network log from Kubearmor
11:25AM INF plugin/kubearmor.go:336 > KubeArmor Relay traffic flow does not exist
11:25AM INF plugin/kubearmor.go:336 > KubeArmor Relay traffic flow does not exist
11:25AM INF networkpolicy/helperFunctions.go:297 > Get network log from Kubearmor
11:25AM INF networkpolicy/helperFunctions.go:297 > Get network log from Kubearmor
11:25AM INF plugin/kubearmor.go:336 > KubeArmor Relay traffic flow does not exist
11:25AM ERR plugin/kubearmor.go:324 > Error connecting kubearmor relay: context deadline exceeded
11:25AM INF plugin/kubearmor.go:486 > watchalerts returning
11:25AM INF plugin/kubearmor.go:405 > watchlogs returning
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xdcc02b]

goroutine 193 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0)
	/home/yasin/go/pkg/mod/google.golang.org/grpc@v1.46.0/clientconn.go:998 +0x4b
github.com/accuknox/auto-policy-discovery/src/plugin.StartKubeArmorRelay.func2.1()
	/home/yasin/Documents/discovery-engine/src/plugin/kubearmor.go:488 +0x57
panic({0x1e53800, 0x31e1360})
	/usr/lib/go-1.18/src/runtime/panic.go:838 +0x207
google.golang.org/grpc.(*ClientConn).NewStream(0x27?, {0x238e760?, 0xc00012a000?}, 0xc0008a7e68?, {0x20dbadb?, 0xc000505a00?}, {0x0?, 0xc0008a7ec0?, 0x477d30?})
	/home/yasin/go/pkg/mod/google.golang.org/grpc@v1.46.0/stream.go:156 +0x38
github.com/kubearmor/KubeArmor/protobuf.(*logServiceClient).WatchAlerts(0xc0008a7f68?, {0x238e760?, 0xc00012a000?}, 0x10000c000876480?, {0x0?, 0x529f2b?, 0xc0005c6e50?})
	/home/yasin/go/pkg/mod/github.com/kubearmor/!kube!armor/protobuf@v0.0.0-20220504043216-6451e04be58b/kubearmor_grpc.pb.go:81 +0x77
github.com/accuknox/auto-policy-discovery/src/plugin.StartKubeArmorRelay.func2()
	/home/yasin/Documents/discovery-engine/src/plugin/kubearmor.go:490 +0xfe
created by github.com/accuknox/auto-policy-discovery/src/plugin.StartKubeArmorRelay
	/home/yasin/Documents/discovery-engine/src/plugin/kubearmor.go:484 +0x415
```

To reproduce this issue:
```
1. git clone https://github.com/accuknox/discovery-engine.git
2. cd discovery-engine/src
3. make
4. CONF_FILE_NAME=local-file ./knoxAutoPolicy
```

**Comment by yasin-cs-ko-ak** [comment]
To resolve this issue:
edit `/etc/hosts` and replace `127.0.0.1 localhost` with `127.0.0.1 kubearmor.kube-system.svc.cluster.local`
